### ISSUE TITLE
Responsive design - opdracht 3: Breakdown schets maken

### ISSUE THREAD

**Issue by Robinwouterson** [Robinwouterson/your-tribe-squad-page#3]
Ik heb een breakdown schets gemaakt van de squadpage waar ik nog aan werk. Het is een schets geeft een blik in hoe het mogelijk eruit zal komen te zien op mobiel (aangeduid op tekening met 'Small') en laptop (angeduid op tekening met 'Large'). Ik ben van plan de CSS Grid te gebruiken of misschien zelfs een combinatie van een Grid en een flexbox eronder door een nieuwe ' div class container' eronder te maken.

Ik verwacht dat het bij de minimale breakpoint tussen 720 en 960 pixels en bij de maximale breakpoint tussen 1160 en 1400 pixels zal ziiten. 

![WhatsApp Image 2024-09-11 at 10 58 15](https://github.com/user-attachments/assets/6106feb1-277a-417e-9d48-07735e4ba556)

**Comment by KoopReynders** [comment]
Per klus, of taak kun je een issue aanmaken waarin je schetsen, breakdown schets, ontwerpen in Figma, feedback en code verzameld. Als je een taak af hebt, sluit je het issue met een link naar de betreffende commit. Dat is gestructureerd werken ...

**Comment by KoopReynders** [comment]
Als je een issue sluit kun je nog een bericht schrijven met wat je hebt gedaan en verwijzen naar code of een commit. Deze issue kan je mooi sluiten als je de CSS Mediaquerie af hebt en een commit hebt gedaan.
